# icons are from https://icon-sets.iconify.design/vscode-icons/
projects:
  - name: ch3nyang-theme
    repo: https://github.com/WCY-dt/ch3nyang-theme
    demo: https://ch3nyang.top/ch3nyang-theme
    description: >-
      A jekyll theme with a simple interface but rich functions. Used for my own blog.
    tech: [Liquid, SCSS, JS]
  - name: MindClip
    repo: https://github.com/WCY-dt/mindclip
    demo: https://mind.ch3nyang.top/
    description: >-
      Short notes for websites, documents and inspiration.
    tech: [ReactJS, TypeScript, JS, Serverless, SQLite]