name: Update github profile with latest blog posts
on:
  workflow_run:
    workflows: ["Deploy Jekyll site to Pages"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Wait for deployment to complete
        run: |
          echo "Waiting for deployment to complete..."
          sleep 120
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: WCY-dt/WCY-dt
          event-type: blog-page-updated
